
GET http://localhost:5045/

###

GET http://localhost:5045/api/categories

###

POST http://localhost:5045/api/categories
Content-Type: application/json

{
    "Name":"Apple and Android",
    "Description":"Apple product find here."
}

###

PUT http://localhost:5045/api/categories/97fce670-4991-4b9b-ba30-5e55b3506d09
Content-Type:application/json

{
    "Name":"Windows Phone",
    "Description":"AAndroid product find here."
}

###

DELETE  http://localhost:5045/api/categories/97fce670-4991-4b9b-ba30-5e55b3506d09

###